# Default values for jitsi
# Declare variables to be passed into your templates.
replicaCount: 1

timezone: Europe/Berlin

default_url: "https://meet.jitsi/"

auth:
  enable: 0
  guests: 1
  type: internal

xmpp:
  domain: meet.jitsi
  auth_domain: meet.jitsi
  muc_domain: muc.meet.jitsi

jicofo:
  component_secret: changeme
  auth:
    user: focus
    password: changeme

jvb:
  auth:
    user: jvb
    password: changeme
  port:
    udp: 30000
    tcp: 30001

ingress:
  enabled: true
  annotations: {}
    ## set certmanager-instance
    # cert-manager.io/cluster-issuer: letsencrypt-prod
    ## make traefik ingress controller redirect to https
    # traefik.ingress.kubernetes.io/redirect-entry-point: https
    ## for use with nginx ingress controller
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  paths: ["/"]
  hosts:
    - meet.jitsi
  tls:
    - secretName: meet.jitsi
      hosts:
        - meet.jitsi
