apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: {{ .Release.Name }}-jvb
  name: {{ .Release.Name }}-jvb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: {{ .Release.Name }}-jvb
    spec:
      containers:
      - env:
        - name: XMPP_SERVER
          value: {{ .Release.Name }}-prosody
        - name: DOCKER_HOST_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: XMPP_DOMAIN
          value: {{ .Values.xmpp.domain }}
        - name: XMPP_AUTH_DOMAIN
          value: {{ .Values.xmpp.auth_domain }}
        - name: JVB_PORT
          value: "30000"
        - name: JVB_TCP_PORT
          value: "30001"
        - name: JVB_AUTH_USER
          value: {{ .Values.jvb.auth.user }}
        - name: JVB_AUTH_PASSWORD
          value: {{ .Values.jvb.auth.password }}
        - name: JVB_BREWERY_MUC
          value: jvbbrewery
        - name: XMPP_INTERNAL_MUC_DOMAIN
          value: internal-muc.meet.jitsi
        - name: JVB_STUN_SERVERS
          value: stun.l.google.com:19302,stun1.l.google.com:19302,stun2.l.google.com:19302
        - name: TZ
          value: {{ .Values.timezone }}
        image: jitsi/jvb
        name: {{ .Release.Name }}-jvb
        ports:
        - containerPort: 30000
          protocol: UDP
        - containerPort: 30001
        resources: {}
      restartPolicy: Always
status: {}
