apiVersion: v1
kind: Service
metadata:
  labels:
    app: jitsi
  name: {{ .Release.Name }}-jvb
spec:
  type: NodePort
  ports:
  - name: udp
    port: {{ .Values.jvb.port.udp }}
    nodePort: {{ .Values.jvb.port.udp }}
    protocol: UDP
    targetPort: {{ .Values.jvb.port.udp }}
  - name: tcp
    port: {{ .Values.jvb.port.tcp }}
    nodePort: {{ .Values.jvb.port.tcp }}
    protocol: TCP
    targetPort: {{ .Values.jvb.port.tcp }}
  selector:
    service: {{ .Release.Name }}-jvb
