apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Release.Name }}-web
  name: {{ .Release.Name }}-web
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 80
  - name: "https"
    port: 443
    targetPort: 443
  selector:
    service: {{ .Release.Name }}-web
