apiVersion: v1
kind: Service
metadata:
  labels:
    service: {{ .Release.Name }}-prosody
  name: {{ .Release.Name }}-prosody
spec:
  ports:
  - name: "xmpp-client2server"
    port: 5222
    targetPort: 5222
  - name: "5280"
    port: 5280
    targetPort: 5280
  - name: "xmpp-component2component"
    port: 5347
    targetPort: 5347
  selector:
    service: {{ .Release.Name }}-prosody
