apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: {{ .Release.Name }}-prosody
  name: {{ .Release.Name }}-prosody
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: {{ .Release.Name }}-prosody
    spec:
      containers:
      - env:
        - name: AUTH_TYPE
          value: {{ .Values.auth.type | default "internal" }}
        - name: ENABLE_AUTH
          value: {{ .Values.auth.enable | default 0 | quote }}
        - name: ENABLE_GUESTS
          value: {{ .Values.auth.guests | default 1 | quote }}
        - name: XMPP_DOMAIN
          value: {{ .Values.xmpp.domain }}
        - name: XMPP_AUTH_DOMAIN
          value: {{ .Values.xmpp.auth_domain }}
        - name: XMPP_MUC_DOMAIN
          value: {{ .Values.xmpp.muc_domain }}
        - name: XMPP_INTERNAL_MUC_DOMAIN
          value: internal-muc.meet.jitsi
        - name: JICOFO_COMPONENT_SECRET
          value: {{ .Values.jicofo.component_secret }}
        - name: JICOFO_AUTH_USER
          value: {{ .Values.jicofo.auth.user }}
        - name: JICOFO_AUTH_PASSWORD
          value: {{ .Values.jicofo.auth.password }}
        - name: JVB_AUTH_USER
          value: {{ .Values.jvb.auth.user }}
        - name: JVB_AUTH_PASSWORD
          value: {{ .Values.jvb.auth.password }}
        - name: JWT_APP_ID
          value: {{ .Values.auth.jwt.app_id }}
        - name: JWT_APP_SECRET
          value: {{ .Values.auth.jwt.app_secret }}
        - name: JWT_ACCEPTED_ISSUERS
          value: {{ .Values.auth.jwt.accepted_issuers }}
        - name: JWT_ACCEPTED_AUDIENCES
          value: {{ .Values.auth.jwt.accepted_audiences }}
        - name: JWT_ASAP_KEYSERVER
          value: {{ .Values.auth.jwt.asap_key_server }}
        - name: JWT_ALLOW_EMPTY
          value: {{ .Values.auth.jwt.allow_empty | default 0 | quote }}
        - name: JWT_AUTH_TYPE
          value: {{ .Values.auth.jwt.auth_type | default "token" }}
        - name: JWT_TOKEN_AUTH_MODULE
          value: {{ .Values.auth.jwt.auth_module | default "token_verification" }}
        - name: TZ
          value: {{ .Values.timezone }}
        image: jitsi/prosody
        name: {{ .Release.Name }}-prosody
        ports:
        - containerPort: 5222
        - containerPort: 5280
        - containerPort: 5347
        resources: {}
{{- if .Values.persistence }}
        volumeMounts:
        - mountPath: /config
          name: data
          subPath: prosody
{{- end }}
      restartPolicy: Always
{{- if .Values.persistence }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pvc
{{- end }}
